@host=localhost
@port=8095
@url=http://{{host}}:{{port}}/api/auth


POST {{url}}/register
Content-Type: application/json

{
    "firstname":"boris",
    "lastname": "rose",
    "email": "boris@gmail.com",
    "password": "caroline"
}

###
# @name Login
POST {{url}}/login
Content-Type: application/json

{
    "email": "boris@gmail.com",
    "password": "caroline"
}


###
GET {{ url }}/me 
Authorization: Bearer {{Login.response.body.token}}